[package]
name = "basic-report"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Roland Schätzle <@roland-KA>"]
license = "MIT"
description = "A simple template for shorter reports"
repository = "https://github.com/roland-KA/basic-report-typst-template"
keywords = ["report", "non-fiction", "basic"]
categories = ["paper", "report"]
exclude = ["CHANGELOG.md"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"